### ISSUE TITLE
Does it support Sign in with GitLab

### ISSUE THREAD

**Issue by LeiHao0** [Kilograpp/Mattermost-iOS-Swift#1]
Hi, I built it successfully on 

macOS 10.12.2 (16C67)
Xcode 8.2.1 (8C1002)

But I didn't find the *Sign in with GitLab* entrance

**Comment by ivedeneev** [comment]
Hello, Artwalk. Currently it doesn't support any login methods but email/password. We will add it in next releases for sure

**Comment by LeiHao0** [comment]
Glad to hear that :)

By the way, would you mind tell me when will the next releases possibly come?

**Comment by ivedeneev** [comment]
with this feature? hard to say. About other - i would say every 2 weeks, but this needs confirmation

**Comment by LeiHao0** [comment]
I read their [Document](https://api.mattermost.com), it says the `User` Object can be get by : 
`curl -i -H 'Authorization: Bearer hyr5dmb1mbb49c44qmx4whniso' http://localhost:8065/api/v3/users/me`


So, it can be add a VC (say GitLabViewController) contained a UIWebView which loading the URL from ServerUrlViewController

Then, in the `UIWebViewDelegate`

```swift
func webViewDidFinishLoad(_ webView: UIWebView) {
    if UserStatusManager.sharedInstance.isSignedIn() {
        dismiss(animated: true) { }
        
        // 1. pop to ServerUrlViewController
        // 2. performSegue(withIdentifier: "showLogin", sender: nil)
        // 3. get User Object by token
    }
}
```

Finally, in `extension Api: UserApi`, add a function

```swift
func login(token: String, completion: @escaping (_ error: Mattermost.Error?) -> Void) {
    let path = UserPathPatternsContainer.loadCurrentUser()
    manager.httpClient.setDefaultHeader("Authorization", value: "Bearer \(token)")
    
    // ... the reset can be as same as  
    // func login(_ email: String, password: String, completion: {})
    
    }, failure: completion)
}
```

Did I miss something? @ivedeneev

**Comment by Mehdzor** [comment]
@Artwalk Gitlab sign in feature is on our roadmap.

**Comment by ivedeneev** [comment]
@Artwalk but pull requests are welcome i guess)
